version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: Vp1357986420
      MYSQL_DATABASE: Finances
    command: --port=3307
    volumes:
      - mysql-data:/var/lib/mysql

  cyrsach:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Vp1357986420
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/Finances
      spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysql

volumes:
  mysql-data:
